version: '3'
services:
  mysql-standalone:
    image: 'mysql:8-oracle'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=miloroot
      - MYSQL_DATABASE=user_credentials
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: franscwa/sprbt
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/user_credentials?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "miloroot"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone


